# Generated by Django 4.2.7 on 2025-11-14 12:48

from django.db import migrations, models
import pdf_processor.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='original_file',
            field=models.FileField(upload_to=pdf_processor.models.pdf_upload_path),
        ),
    ]
